// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGx19mQM_wBzjhKgMcvuz0AbnVp9pYko',
    appId: '1:814221576892:web:6c204cc673034bb56cdeb9',
    messagingSenderId: '814221576892',
    projectId: 'laptopharbor-94baa',
    authDomain: 'laptopharbor-94baa.firebaseapp.com',
    storageBucket: 'laptopharbor-94baa.firebasestorage.app',
    measurementId: 'G-DN313T86MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKeI77JnPXGncbrRkfboBGPeHet37M_e4',
    appId: '1:814221576892:android:30c57db31a96bb876cdeb9',
    messagingSenderId: '814221576892',
    projectId: 'laptopharbor-94baa',
    storageBucket: 'laptopharbor-94baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADiZgZoEhPpu22bNuyfH5bLA1tDnYh2I4',
    appId: '1:814221576892:ios:8aa866061dbe22b76cdeb9',
    messagingSenderId: '814221576892',
    projectId: 'laptopharbor-94baa',
    storageBucket: 'laptopharbor-94baa.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADiZgZoEhPpu22bNuyfH5bLA1tDnYh2I4',
    appId: '1:814221576892:ios:8aa866061dbe22b76cdeb9',
    messagingSenderId: '814221576892',
    projectId: 'laptopharbor-94baa',
    storageBucket: 'laptopharbor-94baa.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxGx19mQM_wBzjhKgMcvuz0AbnVp9pYko',
    appId: '1:814221576892:web:efa263cdf5a5f3036cdeb9',
    messagingSenderId: '814221576892',
    projectId: 'laptopharbor-94baa',
    authDomain: 'laptopharbor-94baa.firebaseapp.com',
    storageBucket: 'laptopharbor-94baa.firebasestorage.app',
    measurementId: 'G-3JL7MJ12W8',
  );
}
